### ISSUE TITLE
DB에 저장될 때 Asia/Seoul로 조정 필요

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#142]
## Description
아이템 저장할 때 한국 시간으로 조정이 필요합니다,,

## To-do
- [ ] RDS 또는 애플리케이션 로직에서 리팩토링이 필요해요!

**Comment by esubine** [comment]
https://cloud-oky.tistory.com/3234
https://programforlife.tistory.com/52

서버와 RDS DB timezone을 UTC에서 KST로 조정했습니다
