### ISSUE TITLE
팔로워/팔로잉 리스트 조회 시 유저 순서 리팩토링이 필요합니다.

### ISSUE THREAD

**Issue by esubine** [linkarchive/Back-End#194]
## Description
팔로워/팔로잉 리스트 조회 시 목록에 본인(API 요청자)이 있다면 가장 상단에 보이도록 정렬?이 필요합니다.

## To-do
- [x] todo  
- [x] todo

**Comment by taegyun1995** [comment]
회의 결과 해당 이슈는 넘어가는걸로 결론이 나왔어요 !
